### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by netpyoung** [netpyoung/SqlCipher4Unity3D#17]
# TODO
- [ ] test environment
  - android / ios / windows / linux / osx
- [ ] sqlcipher 3.x to 4.x
- [ ] sqlcipher build script
- [ ] package manager support
- [ ] apply code formatter
- [ ] refactoring code.
